name: 'Upload Security Report to DefectDojo'
description: 'Sube reporte de seguridad a DefectDojo y lo asocia a un engagement.'
inputs:
  defectdojo_user:
    description: 'Usuario de DefectDojo'
    required: true
  defectdojo_password:
    description: 'Contraseña de DefectDojo'
    required: true
  product_id:
    description: 'ID del producto en DefectDojo'
    required: true
  release_name:
    description: 'Nombre del engagement'
    required: true
  scan_type:
    description: 'Tipo de escaneo'
    required: true
  enviroment:
    description: 'Entorno'
    required: true
  report:
    description: 'Reporte a escanear'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Extraer URL de DefectDojo desde Route.yaml
      shell: bash
      run: |
        DEFECTDOJO_URL=$(grep '^\s*host:' "${GITHUB_WORKSPACE}/charts/dojo/route.yml" | sed 's/.*host: //g' | tr -d '[:space:]')
        echo "DEFECTDOJO_URL=https://${DEFECTDOJO_URL}"  >> $GITHUB_ENV
        
    - name: Dar permisos de ejecución a entrypoint.sh
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.sh
      
    - name: Ejecutar script de subida a DefectDojo
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        DEFECTDOJO_URL: ${{ env.DEFECTDOJO_URL }}
        DEFECTDOJO_USER: ${{ inputs.defectdojo_user }}
        DEFECTDOJO_PASSWORD: ${{ inputs.defectdojo_password }}
        PRODUCT_ID: ${{ inputs.product_id }}
        ENGAGEMENT_NAME: ${{ inputs.release_name }}
        SCAN_TYPE: ${{ inputs.scan_type }}
        REPORT: ${{ inputs.report }}
