name: 'Upload Security Report to DefectDojo'
description: 'Sube reporte de seguridad a DefectDojo y lo asocia a un engagement.'
inputs:
  defectdojo_url:
    description: 'URL de DefectDojo'
    required: true
  product_type_name:
    description: 'Tipo de producto en DefectDojo'
    required: true
  product_name:
    description: 'Nombre del producto en DefectDojo'
    required: true
  release_name:
    description: 'Nombre del engagement'
    required: true
  scan_type:
    description: 'Tipo de escaneo'
    required: true
  version:
    description: 'Version'
    required: true
  enviroment:
    description: 'Entorno'
    required: true
  version:
    description: 'Version'
    required: true
  report:
    description: 'Reporte a escanear'
    required: true
  title_scan:
    description: 'Título del escaner'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Dar permisos de ejecución a entrypoint.sh
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.sh
      
    - name: Ejecutar script de subida a DefectDojo
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        DEFECTDOJO_URL: ${{ inputs.defectdojo_url }}
        DEFECTDOJO_USER: ${{ env.defectdojo_user }}
        DEFECTDOJO_PASSWORD: ${{ env.defectdojo_password }}
        PRODUCT_TYPE_NAME: ${{ inputs.product_type_name }}
        PRODUCT_NAME: ${{ inputs.product_name }}
        VERSION: ${{ inputs.version }}
        ENVIRONMENT: ${{ inputs.enviroment }}    
        ENGAGEMENT_NAME: ${{ inputs.release_name }}
        VERSION: ${{ inputs.version }}
        SCAN_TYPE: ${{ inputs.scan_type }}
        TITLE_SCAN: ${{ inputs.title_scan }}
        REPORT: ${{ inputs.report }}
