name: Test Upload Security Report to DefectDojo

on:
  workflow_dispatch:

jobs:
  upload_report:
    name: Upload Report to DefectDojo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Simular Artifact 
        run: |
          if [ ! -f report_xml.xml ]; then
            echo " Error: No encuentra el archivo"
            exit 1
          fi

      - name: Subir reporte a DefectDojo
        uses: ./.github/actions/upload-security-report
        with:
          defectdojo_url: "https://dojo.ez-ibm-openshift-vpc-b9be9ed6ae33d743815245d0b773ebc7-0000.eu-es.containers.appdomain.cloud/"
          product_type_name: "Prueba claudia"
          product_name: "Prueba claudia"
          release_name: "Prueba Claudia"
          scan_type: "ZAP Scan"
          version: "1.0.0"
          enviroment: "Development"
          report: "./report_xml.xml"
        env:
          defectdojo_user: ${{ secrets.DEFECTDOJO_USER }}
          defectdojo_password: ${{ secrets.DEFECTDOJO_PASSWORD }}
        
